name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'

    - name: Build
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          go build -o staticfish-cli.exe main.go
        else
          go build -o staticfish-cli main.go
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: staticfish-cli-${{ runner.os }}
        path: |
          staticfish-cli
          staticfish-cli.exe
        if-no-files-found: ignore
